"""empty message

Revision ID: 8f945d77b546
Revises: 6a1d847aadac
Create Date: 2025-02-11 01:01:27.468497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f945d77b546'
down_revision = '6a1d847aadac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dm_cache', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dm_cache', schema=None) as batch_op:
        batch_op.drop_column('country_name')

    # ### end Alembic commands ###
