"""empty message

Revision ID: 932b4f858b33
Revises: 17938401e9b9
Create Date: 2025-02-13 14:10:59.059728

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '932b4f858b33'
down_revision = '17938401e9b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payout', schema=None) as batch_op:
        batch_op.alter_column('transaction_id',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.drop_index('payment_id')
        batch_op.drop_constraint('payout_ibfk_3', type_='foreignkey')
        batch_op.create_foreign_key(None, 'storefront', ['storefront_id'], ['id'])
        batch_op.drop_column('payment_id')
        batch_op.drop_column('seller_id')

    with op.batch_alter_table('storefront', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payout_method', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('storefront', schema=None) as batch_op:
        batch_op.drop_column('payout_method')

    with op.batch_alter_table('payout', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seller_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('payment_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('payout_ibfk_3', 'user', ['seller_id'], ['id'])
        batch_op.create_index('payment_id', ['payment_id'], unique=True)
        batch_op.alter_column('transaction_id',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###
