"""empty message

Revision ID: 9b325ed7ce9f
Revises: bb1e88d98ac0
Create Date: 2025-02-12 17:17:59.510110

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9b325ed7ce9f'
down_revision = 'bb1e88d98ac0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('shipping_address_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('payment_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('payment_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('shipping_address_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
