"""Allow storefront without business_info_id

Revision ID: b306b39d2587
Revises: 8f945d77b546
Create Date: 2025-02-12 13:00:06.271254

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b306b39d2587'
down_revision = '8f945d77b546'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('storefront', schema=None) as batch_op:
        batch_op.alter_column('business_info_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('storefront', schema=None) as batch_op:
        batch_op.alter_column('business_info_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
