"""empty message

Revision ID: e444dd341a15
Revises: b306b39d2587
Create Date: 2025-02-12 13:44:58.056244

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e444dd341a15'
down_revision = 'b306b39d2587'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_storefront', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('user_storefront_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('seller_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_storefront', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seller_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_storefront_ibfk_1', 'seller', ['seller_id'], ['user_id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
